var express = require("express");
const router = express.Router();
const ProductRouter = require("../product/product");
const ProductWbRouter = require("../productWeb/productWb");
const SiteInfoRouter = require("../siteInfo/siteInfo");
const LikeWbRouter = require("../likeWeb/likeWb");
const ScoreWbRouter = require("../scoreWeb/scoreWb");
const FaqRouter = require("../faq/faq");
const FaqWbRouter = require("../faqWeb/faqWb");
const FactorRouter = require("../factor/factor");
const FactorDetailRouter = require("../factorDetail/factorDetail");
const DiscountRouter = require("../discount/discount");
const CommentRouter = require("../comment/comment");
const CommentWbRouter = require("../commentWeb/commentWb");
const ProductContorllerRouter = require("../controllers/productController");
const DiscountContorllerRouter = require("../controllers/discountController");
module.exports = function (app) {
  app.use("/api/products", ProductRouter);
  app.use("/api/wbproducts", ProductWbRouter);
  app.use("/api/siteinfos", SiteInfoRouter);
  app.use("/api/wblikes", LikeWbRouter);
  app.use("/api/wbscores", ScoreWbRouter);
  app.use("/api/faqs", FaqRouter);
  app.use("/api/wbfaqs", FaqWbRouter);
  app.use("/api/factors", FactorRouter);
  app.use("/api/factordetails", FactorDetailRouter);
  app.use("/api/discounts", DiscountRouter);
  app.use("/api/comments", CommentRouter);
  app.use("/api/wbcomments", CommentWbRouter);

  app.use("/products", ProductContorllerRouter);
  app.use("/discounts", DiscountContorllerRouter);
};
